### ISSUE TITLE
SDK现在不可用是吗

### ISSUE THREAD

**Issue by ZhangBohan** [leancloud/python-sdk#10]
python setup.py test
```
running test
running egg_info
writing requirements to leancloud_sdk.egg-info/requires.txt
writing leancloud_sdk.egg-info/PKG-INFO
writing top-level names to leancloud_sdk.egg-info/top_level.txt
writing dependency_links to leancloud_sdk.egg-info/dependency_links.txt
reading manifest file 'leancloud_sdk.egg-info/SOURCES.txt'
writing manifest file 'leancloud_sdk.egg-info/SOURCES.txt'
running build_ext
tests.test_avobject.test_extend ... ERROR
tests.test_avobject.test_class_extend ... ERROR
tests.test_avobject.test_set ... ERROR
tests.test_avobject.test_get ... ERROR
tests.test_avobject.test_save ... ERROR
tests.test_avquery.test_basic_query ... ERROR
tests.test_geo_point.test_invalid ... ok
tests.test_geo_point.test_setter ... ok
tests.test_geo_point.test_dump ... ok
tests.test_geo_point.test_radians_to ... ok
tests.test_geo_point.test_eq ... ok

======================================================================
ERROR: tests.test_avobject.test_extend
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/python-sdk/tests/test_avobject.py", line 21, in test_extend
    ok_(Object.extend('Album'))
AttributeError: type object 'Object' has no attribute 'extend'

======================================================================
ERROR: tests.test_avobject.test_class_extend
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/python-sdk/tests/test_avobject.py", line 28, in test_class_extend
    assert 'title' in Album._fields
AttributeError: type object 'Album' has no attribute '_fields'

======================================================================
ERROR: tests.test_avobject.test_set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/python-sdk/tests/test_avobject.py", line 32, in test_set
    Album = Object.extend('Album')
AttributeError: type object 'Object' has no attribute 'extend'

======================================================================
ERROR: tests.test_avobject.test_get
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/python-sdk/tests/test_avobject.py", line 40, in test_get
    Album = Object.extend('Album')
AttributeError: type object 'Object' has no attribute 'extend'

======================================================================
ERROR: tests.test_avobject.test_save
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/python-sdk/tests/test_avobject.py", line 49, in test_save
    Album = Object.extend('Album')
AttributeError: type object 'Object' has no attribute 'extend'

======================================================================
ERROR: tests.test_avquery.test_basic_query
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 267, in setUp
    try_run(self.test, names)
  File "/Library/Python/2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/private/tmp/python-sdk/tests/test_avquery.py", line 26, in setup_func
    albums = Query(GameScore).find()
  File "/private/tmp/python-sdk/leancloud/query.py", line 105, in find
    result = rest.get('/classes/{}'.format(self._query_class._class_name), self.dump())
AttributeError: type object 'GameScore' has no attribute '_class_name'

----------------------------------------------------------------------
Ran 11 tests in 0.100s

FAILED (errors=6)
```

**Comment by akinLiu** [comment]
什么时候python sdk 可以用那

**Comment by aisk** [comment]
@akinLiu 第一版的主要功能都已经实现，现在是在bugfix阶段。如果你是在自己服务器上用Python SDK的话，可以尝试使用了，欢迎反馈bug和提交PR。

**Comment by aisk** [comment]
@ZhangBohan @akinLiu @filod 现在功能基本都是可用的了，正在进行发布前的 code review，相关文档也在 review，可以参考：https://github.com/aisk/leancloud-docs/blob/python/md/python_guide.md。欢迎各位有兴趣的一块来 review 或者试用，发现 bug 请提 issue。

**Comment by ZhangBohan** [comment]
@aisk 太棒了，回头拜读一下源码，学习学习
