### ISSUE TITLE
leancloud.File   save()   TypeError

### ISSUE THREAD

**Issue by JianxunRao** [leancloud/python-sdk#264]
Error occurs when I simply upload a file to leancloud:   
```
leancloud.init('******************', '******************')
with open('./cants.txt') as f:
    pic_avfile = leancloud.File('cants.txt', f)
    pic_avfile.save()
    print pic_avfile.url
```
Error Log:
```
Traceback (most recent call last):
  File "D:/PycharmProjects/IMoqi/local_test.py", line 52, in <module>
    pic_avfile.save()
  File "C:\Python27\lib\site-packages\leancloud\file_.py", line 209, in save
    self._save_to_qiniu(content['token'], content['key'])
  File "C:\Python27\lib\site-packages\leancloud\file_.py", line 154, in _save_to_qiniu
    ret, info = qiniu.put_data(uptoken, key, self._source)
  File "C:\Python27\lib\site-packages\qiniu\services\storage\uploader.py", line 30, in put_data
    return _form_put(up_token, key, data, params, mime_type, crc, progress_handler, fname)
  File "C:\Python27\lib\site-packages\qiniu\services\storage\uploader.py", line 80, in _form_put
    url = config.get_default('default_zone').get_up_host_by_token(up_token) + '/'
  File "C:\Python27\lib\site-packages\qiniu\zone.py", line 30, in get_up_host_by_token
    up_hosts = self.get_up_host(ak, bucket)
  File "C:\Python27\lib\site-packages\qiniu\zone.py", line 49, in get_up_host
    bucket_hosts = self.get_bucket_hosts(ak, bucket)
  File "C:\Python27\lib\site-packages\qiniu\zone.py", line 71, in get_bucket_hosts
    bucket_hosts = self.get_bucket_hosts_to_cache(key)
  File "C:\Python27\lib\site-packages\qiniu\zone.py", line 91, in get_bucket_hosts_to_cache
    self.host_cache_from_file()
  File "C:\Python27\lib\site-packages\qiniu\zone.py", line 107, in host_cache_from_file
    path = self.host_cache_file_path()
  File "C:\Python27\lib\site-packages\qiniu\zone.py", line 124, in host_cache_file_path
    return home + "/.qiniu_pythonsdk_hostscache.json"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
It seems not problem in my code. Whats wrong with it? Pls help me. thx :)

**Comment by aisk** [comment]
Hi, I found this is a qiniu SDK's bug, and there was already a issue in qiniu SDK's repo: https://github.com/qiniu/python-sdk/issues/225

Before qiniu resolve this problem, you can set a `HOME` environment variable manually before run your codes.

**Comment by aisk** [comment]
Closed via https://github.com/qiniu/python-sdk/pull/237
