### ISSUE TITLE
关于SSL证书验证失败的问题

### ISSUE THREAD

**Issue by vinci7** [leancloud/python-sdk#310]
```
pi@raspberrypi:~/Downloads $ python3 LeanCloudGetCC98.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 237, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 123, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 543, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LeanCloudGetCC98.py", line 44, in <module>
    raise e
  File "LeanCloudGetCC98.py", line 20, in <module>
    query_count = query.equal_to('id', str(i['id'])).count()
  File "/usr/local/lib/python3.4/dist-packages/leancloud/query.py", line 245, in count
    response = client.get('/classes/{0}'.format(self._query_class._class_name), params)
  File "/usr/local/lib/python3.4/dist-packages/leancloud/client.py", line 90, in new_func
    return func(headers=headers, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/leancloud/client.py", line 147, in new_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/leancloud/client.py", line 196, in get
    hooks=request_hooks,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**平台：**
Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux

**软件版本：**
pi@raspberrypi:~ $ pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)
pi@raspberrypi:~ $ python3 --version
Python 3.4.2

**报错：**
SSL CERTIFICATE_VERIFY_FAILED certificate verify failed (_ssl.c:600)

**临时解决方案：**
leancloud/client.py

```
@need_init
@check_error
def get(url, params=None, headers=None):
    if not params:
        params = {}
    else:
        for k, v in iteritems(params):
            if isinstance(v, dict):
                params[k] = json.dumps(v, separators=(',', ':'))
    response = session.get(
        get_url(url),
        headers=headers,
        params=params,
        timeout=TIMEOUT_SECONDS,
        hooks=request_hooks,
        **verify=False,**
    )
    return response
```

关闭验证。

在mac上调试的时候是正常的，在树莓派上跑起来会报这个错误。
不知道正确的解决方案，求指教，谢谢！

**Comment by aisk** [comment]
您好，如果在 mac 上正常使用的话，这个应该不是 SDK 本身的问题，请尝试自己解决。
