### ISSUE TITLE
本地运行云引擎报错KeyError: u'session_token'

### ISSUE THREAD

**Issue by BadReese** [leancloud/python-sdk#378]
Traceback (most recent call last):
  File "/Users/johnreese/Development/Python/Duton's/venv/lib/python2.7/site-packages/leancloud/engine/cookie_session.py", line 59, in __call__
    self.pre_process(environ)
  File "/Users/johnreese/Development/Python/Duton's/venv/lib/python2.7/site-packages/leancloud/engine/cookie_session.py", line 80, in pre_process
    user._session_token = session['session_token']
KeyError: u'session_token'
美国节点，请问啥问题？

**Comment by BadReese** [comment]
@aisk

**Comment by juvenn** [comment]
@BadReese 是什么原因导致的，找到解决方法了吗？
