### ISSUE TITLE
LeanCloudError: [1] Please provide a valid timestamp for max_ts  输入python3默认的的datetime格式的数据不行，需要什么格式呢？

### ISSUE THREAD

**Issue by chaim1986** [leancloud/python-sdk#388]
...     now = datetime.now()
...     dt = datetime(now.year,now.month,now.day)
...     print(dt)
...     message = leancloud.Message()
...    messages = message.find_by_conversation("5bc304ad60d9007f7ba79091",10,True,dt)

```

DEBUG:urllib3.connectionpool:Resetting dropped connection: x5auvr7e.api.lncld.net
DEBUG:urllib3.connectionpool:https://x5auvr7e.api.lncld.net:443 "GET /1.1/rtm/messages/history?reversed=True&limit=10&convid=5bc304ad60d9007f7ba79091&max_ts=1539532800000.0 HTTP/1.1" 400 None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chaim/.pyenv/versions/3.5.3/lib/python3.5/site-packages/leancloud/message.py", line 72, in find_by_conversation
    return list(cls._find(query_params))
  File "/Users/chaim/.pyenv/versions/3.5.3/lib/python3.5/site-packages/leancloud/message.py", line 40, in _find
    content = client.get('/rtm/messages/history', params=query_params).json()
  File "/Users/chaim/.pyenv/versions/3.5.3/lib/python3.5/site-packages/leancloud/client.py", line 96, in new_func
    return func(headers=headers, *args, **kwargs)
  File "/Users/chaim/.pyenv/versions/3.5.3/lib/python3.5/site-packages/leancloud/client.py", line 161, in new_func
    raise leancloud.LeanCloudError(content.get('code', 1), content.get('error', 'Unknown Error'))
leancloud.errors.LeanCloudError: LeanCloudError: [1] Please provide a valid timestamp for max_ts.
```

**Comment by chaim1986** [comment]
@classmethod
    def find_by_conversation(cls, conversation_id, limit=None, reversed=None, before_time=None, before_message_id=None):
        # type: (str, Optional[int], Optional[bool], Optional[Union[datetime, float]], Optional[str]) -> List[Message]
        """获取某个对话中的聊天记录

=========== sdk源码里面显示浮点和datetime应该都可以 不知道api 执行的时候出啥问题了？

**Comment by chaim1986** [comment]
原因：api接受的是整型数据，而目前sdk提供的是浮点数
已经提交修改代码。https://github.com/leancloud/python-sdk/pull/389#pullrequestreview-165909731
