### ISSUE TITLE
miss dependency `werkzeug`

### ISSUE THREAD

**Issue by weakish** [leancloud/python-sdk#410]
leancloud should list werkzeug as its dependency.

```sh
Traceback (most recent call last):
  File "fm163.py", line 15, in <module>
    import leancloud
  File "/home/weakish/.local/lib/python3.6/site-packages/leancloud/__init__.py", line 19, in <module>
    from . import client
  File "/home/weakish/.local/lib/python3.6/site-packages/leancloud/client.py", line 18, in <module>
    from leancloud import utils
  File "/home/weakish/.local/lib/python3.6/site-packages/leancloud/utils.py", line 16, in <module>
    from werkzeug import LocalProxy
ImportError: cannot import name 'LocalProxy'
```

**Comment by weakish** [comment]
好吧，又是我的锅，`setup.py` 里少了一个逗号……（依稀记得当初随手在 vim 里改，没开 IDE）

这会导致云引擎 django 模板项目无法部署（flask 因为天然依赖 werkzeug 凑巧避开了这个 bug）

**Comment by ywzhaiqi** [comment]
pip 安装的 2.5.0 版本还有这个问题

**Comment by weakish** [comment]
@ywzhaiqi 感谢报告问题。现在可以临时在 requirements.txt 里指定 Werkzeug 的版本为 `>=0.11.11,<1.0.0`，我们近期会发布一个 SDK 的新版本，修复这个问题。
