### ISSUE TITLE
关于长连接(>3天)

### ISSUE THREAD

**Issue by Sheey11** [leancloud/python-sdk#445]
```
[2020-03-05 06:11:07][ERROR]	Error encountered:
[2020-03-05 06:11:07][ERROR]	Traceback (most recent call last):
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[2020-03-05 06:11:07][ERROR]	    httplib_response = self._make_request(conn, method, url,
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 344, in _make_request
[2020-03-05 06:11:07][ERROR]	    self._validate_conn(conn)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
[2020-03-05 06:11:07][ERROR]	    conn.connect()
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
[2020-03-05 06:11:07][ERROR]	    self.sock = ssl_wrap_socket(
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
[2020-03-05 06:11:07][ERROR]	    return context.wrap_socket(sock, server_hostname=server_hostname)
[2020-03-05 06:11:07][ERROR]	  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
[2020-03-05 06:11:07][ERROR]	    return self.sslsocket_class._create(
[2020-03-05 06:11:07][ERROR]	  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
[2020-03-05 06:11:07][ERROR]	    self.do_handshake()
[2020-03-05 06:11:07][ERROR]	  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
[2020-03-05 06:11:07][ERROR]	    self._sslobj.do_handshake()
[2020-03-05 06:11:07][ERROR]	ConnectionResetError: [Errno 104] Connection reset by peer
[2020-03-05 06:11:07][ERROR]
[2020-03-05 06:11:07][ERROR]	During handling of the above exception, another exception occurred:
[2020-03-05 06:11:07][ERROR]
[2020-03-05 06:11:07][ERROR]	Traceback (most recent call last):
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
[2020-03-05 06:11:07][ERROR]	    resp = conn.urlopen(
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 640, in urlopen
[2020-03-05 06:11:07][ERROR]	    retries = retries.increment(method, url, error=e, _pool=self,
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 368, in increment
[2020-03-05 06:11:07][ERROR]	    raise six.reraise(type(error), error, _stacktrace)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 685, in reraise
[2020-03-05 06:11:07][ERROR]	    raise value.with_traceback(tb)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 600, in urlopen
[2020-03-05 06:11:07][ERROR]	    httplib_response = self._make_request(conn, method, url,
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 344, in _make_request
[2020-03-05 06:11:07][ERROR]	    self._validate_conn(conn)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
[2020-03-05 06:11:07][ERROR]	    conn.connect()
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
[2020-03-05 06:11:07][ERROR]	    self.sock = ssl_wrap_socket(
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
[2020-03-05 06:11:07][ERROR]	    return context.wrap_socket(sock, server_hostname=server_hostname)
[2020-03-05 06:11:07][ERROR]	  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
[2020-03-05 06:11:07][ERROR]	    return self.sslsocket_class._create(
[2020-03-05 06:11:07][ERROR]	  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
[2020-03-05 06:11:07][ERROR]	    self.do_handshake()
[2020-03-05 06:11:07][ERROR]	  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
[2020-03-05 06:11:07][ERROR]	    self._sslobj.do_handshake()
[2020-03-05 06:11:07][ERROR]	urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2020-03-05 06:11:07][ERROR]
[2020-03-05 06:11:07][ERROR]	During handling of the above exception, another exception occurred:
[2020-03-05 06:11:07][ERROR]
[2020-03-05 06:11:07][ERROR]	Traceback (most recent call last):
[2020-03-05 06:11:07][ERROR]	  File "valine-checker.py", line 142, in main
[2020-03-05 06:11:07][ERROR]	    lst = await check_new_comments()
[2020-03-05 06:11:07][ERROR]	  File "valine-checker.py", line 18, in check_new_comments
[2020-03-05 06:11:07][ERROR]	    unnotified_list = query.find()
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/leancloud/query.py", line 222, in find
[2020-03-05 06:11:07][ERROR]	    content = self._do_request(self.dump())
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/leancloud/query.py", line 182, in _do_request
[2020-03-05 06:11:07][ERROR]	    return client.get('/classes/{0}'.format(self._query_class._class_name), params).json()
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/leancloud/client.py", line 105, in new_func
[2020-03-05 06:11:07][ERROR]	    return func(headers=headers, *args, **kwargs)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/leancloud/client.py", line 162, in new_func
[2020-03-05 06:11:07][ERROR]	    response = func(*args, **kwargs)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/leancloud/client.py", line 207, in get
[2020-03-05 06:11:07][ERROR]	    response = session.get(
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
[2020-03-05 06:11:07][ERROR]	    return self.request('GET', url, **kwargs)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
[2020-03-05 06:11:07][ERROR]	    resp = self.send(prep, **send_kwargs)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
[2020-03-05 06:11:07][ERROR]	    r = adapter.send(request, **kwargs)
[2020-03-05 06:11:07][ERROR]	  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
[2020-03-05 06:11:07][ERROR]	    raise ConnectionError(err, request=request)
[2020-03-05 06:11:07][ERROR]	requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[2020-03-05 06:11:07][ERROR]
```
`leancloud.init` 之后大概 3 天就这样了，是需要重新 `init`？还是有自带的方法重连？

**Comment by weakish** [comment]
> ConnectionResetError: [Errno 104] Connection reset by peer-

从这个报错来看应该是网络断了。

Python SDK 并没有长连接机制，比如 `obj.save()` 就是发一个 POST 的 HTTP 请求，遇到这类网络错误也不会自动重连。
如果想要重试，可以自行 except 相关的异常，然后重试失败的操作。
