### ISSUE TITLE
请问可以指导开发者如何创建测试应用吗？

### ISSUE THREAD

**Issue by Ma233** [leancloud/python-sdk#517]
在 leancloud 新建一个测试应用，配置了 `APP_ID`，`APP_KEY`，`MASTER_KEY`，`USE_REGION` 后，执行 `python -m nose` 发现很多测试用例由于测试应用未提前配置无法执行。比如下面这个测试因为云引擎中没有声明 add 函数而报错:

```python
def test_client():  # type: () -> None
    assert cloud.run("add", a=1, b=2) == 3
```

报错：
```
(venv) ➜  leancloud-python-sdk git:(master) ✗ python -m nose -v --nocapture tests/test_engine.py:test_client
tests.test_engine.test_client ... ERROR

======================================================================
ERROR: tests.test_engine.test_client
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/magine/XT/codes/leancloud-python-sdk/venv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/magine/XT/codes/leancloud-python-sdk/tests/test_engine.py", line 530, in test_client
    assert cloud.run("add", a=1, b=2) == 3
  File "/Users/magine/XT/codes/leancloud-python-sdk/leancloud/cloud.py", line 26, in run
    response = leancloud.client.post(
  File "/Users/magine/XT/codes/leancloud-python-sdk/leancloud/client.py", line 109, in new_func
    return func(headers=headers, *args, **kwargs)
  File "/Users/magine/XT/codes/leancloud-python-sdk/leancloud/client.py", line 172, in new_func
    content = response.json()
  File "/Users/magine/XT/codes/leancloud-python-sdk/venv/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/magine/.pyenv/versions/3.8.6/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/magine/.pyenv/versions/3.8.6/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/magine/.pyenv/versions/3.8.6/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): app-router.com:443
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): xfxfe4qh.engine.lncld.net:443
urllib3.connectionpool: DEBUG: https://xfxfe4qh.engine.lncld.net:443 "POST /1.1/functions/add HTTP/1.1" 400 22
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.247s

FAILED (errors=1)
```

此外还有一些报错是因为 GameScore 表未提前创建导致的；以及一些其他报错。

**Comment by Ma233** [comment]
如果可以的话，希望可以给出测试用的云引擎代码，和 schema。

**Comment by weakish** [comment]
其实新建应用来测试是比较麻烦的，现在的 sdk 测试里有很多测试是依赖应用的状态的。

附件是导出的测试应用的 schema 

[8FfQwpvihLHK4htqmtEvkNrv-export78YI34Jo14094351105209676.tar.gz](https://github.com/leancloud/python-sdk/files/6582523/8FfQwpvihLHK4htqmtEvkNrv-export78YI34Jo14094351105209676.tar.gz)

测试应用现在用的云引擎代码年代比较久远（node.js 0.12 时期），里面包含了一些现在不推荐的写法，不太方便公开。您可以跳过云引擎相关测试，或者根据测试内容自行编写相应的云引擎代码。

**Comment by Ma233** [comment]
您好，我刚才翻看了一下你们 travis 中的配置信息（在 README.md 中有相关链接），从里面找到了对应的环境变量可以跑通测试，不知道我用来跑本地测试是否会影响到你们？

**Comment by weakish** [comment]
如果不是特别频繁地跑测试的话，可以直接用 https://github.com/leancloud/python-sdk/blob/master/.github/workflows/pythonpackage.yml#L60 中的 key（和 travis 环境变量中的 key 是一样的，travis 是以前用的 CI，后来换到了 github action），这样就不用自己折腾测试应用了。

**Comment by weakish** [comment]
最近重建了测试应用，现在 github workflow 中的 key 已经隐藏。旧的测试应用已经不可用。

在 README 补充了搭测试应用时的相关控制台配置，可以参考。

这个 issue 先关了，如果还遇到问题，可以再开 issue。
